### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by TimerPVP** [TheComputerGeek2/MagicSpells#263]
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.nisovin.magicspells.MagicSpells$1.execute(MagicSpells.java:1045)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235)
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202)
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198)
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:991)
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26)
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/bukkit/block/data/BlockData
	at com.nisovin.magicspells.CastListener.onPlayerInteract(CastListener.java:80)
	... 22 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.block.data.BlockData
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 23 more

java.lang.NoClassDefFoundError: org/bukkit/block/data/BlockData
	at com.nisovin.magicspells.CastListener.onPlayerInteract(CastListener.java:80)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.nisovin.magicspells.MagicSpells$1.execute(MagicSpells.java:1045)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235)
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202)
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198)
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:991)
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26)
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.bukkit.block.data.BlockData
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 23 more

java.lang.ClassNotFoundException: org.bukkit.block.data.BlockData
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.nisovin.magicspells.CastListener.onPlayerInteract(CastListener.java:80)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.nisovin.magicspells.MagicSpells$1.execute(MagicSpells.java:1045)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235)
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202)
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198)
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:991)
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26)
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
	at java.lang.Thread.run(Unknown Source)

Server version: git-Spigot-dcd1643-e60fc34 (MC: 1.12.2)
MagicSpells version: 4.0-Beta-4

**Comment by JasperLorelai** [comment]
MagicSpells 4.0 versions are intented to work on 1.13-1.15.2 (although my prediction is that beta 7 will work on 1.16.x+).
