### ISSUE TITLE
Error on Mohist 1.16.4

### ISSUE THREAD

**Issue by nolway** [TheComputerGeek2/MagicSpells#390]
Hello I have this error when I start my server (Mohist 1.16.4 build 200) with MagicSpells 4.0 beta 8 : 

`[16:42:40 ERROR]: Error occurred while enabling MagicSpells v4.0-Beta-8 (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at java.util.AbstractMap.put(AbstractMap.java:209) ~[?:?] {}
        at net.minecraft.item.crafting.RecipeManager.addRecipe(RecipeManager.java:85) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftFurnaceRecipe.addToCraftingManager(CraftFurnaceRecipe.java:28) ~[forge:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.addRecipe(CraftServer.java:1199) ~[forge:?] {re:classloading}
        at org.bukkit.Bukkit.addRecipe(Bukkit.java:714) ~[forge:?] {re:classloading}
        at com.nisovin.magicspells.handlers.RecipeHandler.clearRecipes(RecipeHandler.java:204) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at com.nisovin.magicspells.MagicSpells.load(MagicSpells.java:387) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at com.nisovin.magicspells.MagicSpells.onEnable(MagicSpells.java:188) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:491) ~[forge:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:405) ~[forge:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:445) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:364) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:217) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:747) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:275) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:834) [?:?] {}`

**Comment by Chronoken** [comment]
You are using a hybrid server software (plugins + mods), it's not supported, it's gonna cause issues with other plugins and it's not an issue we can fix.
You should try reporting the issue to the Mohist devs.
