### ISSUE TITLE
java.lang.NoSuchMethodError: org.bukkit.World.getNearbyLivingEntities(Lorg/bukkit/Location;DDD)Ljava/util/Collection

### ISSUE THREAD

**Issue by zhjlee11** [TheComputerGeek2/MagicSpells#400]
Bukkit : Spigot 1.16.4
Minecraft Version : 1.16.4
EffectLib Version : 6.4
MagicSpell Version : 4.0 Beta-8

When I cast PP skills, the error is generated.

```
[Server thread/WARN]: [MagicSpells] Task #9 for MagicSpells v4.0-Beta-8 generated an exception
java.lang.NoSuchMethodError: org.bukkit.World.getNearbyLivingEntities(Lorg/bukkit/Location;DDD)Ljava/util/Collection;
        at com.nisovin.magicspells.util.ProjectileTracker.checkHitbox(ProjectileTracker.java:502) ~[?:?]
        at com.nisovin.magicspells.util.ProjectileTracker.run(ProjectileTracker.java:397) ~[?:?]
        at com.nisovin.magicspells.MagicSpells.lambda$scheduleRepeatingTask$5(MagicSpells.java:1309) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1059) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222-2-ojdkbuild]
```

I tried 1.14.4, 1.15.2, 1.16, 1.16.2, but all versions are generate the same error.
Also, I apply only two plugins(MagicSpell, EffectLib)

**Comment by LillyCG** [comment]
switch to papermc or any fork of papermc

**Comment by zhjlee11** [comment]
> switch to papermc or any fork of papermc

Thanks! It works!
