### ISSUE TITLE
NPE on default forcebomb spell

### ISSUE THREAD

**Issue by SXRWahrheit** [TheComputerGeek2/MagicSpells#50]
```
[11:46:56] [Server thread/INFO]: Wahrheit issued server command: /cast forcebomb
[11:46:56] [Server thread/INFO]: [PLAYERCOMMAND} Wahrheit: [-5149 70 6367] => "/cast forcebomb"
[11:46:56] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cast' in plugin MagicSpells v3.5-dev-1708041909
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-65e8124-357b573]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-65e8124-357b573]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[server.jar:git-Spigot-65e8124-357b573]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1386) [server.jar:git-Spigot-65e8124-357b573]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1221) [server.jar:git-Spigot-65e8124-357b573]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-65e8124-357b573]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-65e8124-357b573]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-65e8124-357b573]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-65e8124-357b573]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-65e8124-357b573]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-65e8124-357b573]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-65e8124-357b573]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-65e8124-357b573]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.LivingEntity.getTargetBlock(Ljava/util/HashSet;I)Lorg/bukkit/block/Block;
	at com.nisovin.magicspells.util.BlockUtils.getTargetBlock(BlockUtils.java:42) ~[?:?]
	at com.nisovin.magicspells.Spell.getTargetedBlock(Spell.java:1900) ~[?:?]
	at com.nisovin.magicspells.spells.targeted.ForcebombSpell.castSpell(ForcebombSpell.java:45) ~[?:?]
	at com.nisovin.magicspells.Spell.handleCast(Spell.java:1272) ~[?:?]
	at com.nisovin.magicspells.Spell.cast(Spell.java:1196) ~[?:?]
	at com.nisovin.magicspells.Spell.cast(Spell.java:1186) ~[?:?]
	at com.nisovin.magicspells.CastCommand.onCommand(CastCommand.java:321) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-65e8124-357b573]
	... 15 more
```

**Comment by TheComputerGeek2** [comment]
Missing versions, MagicSpells, Effectlib, Spigot.

**Comment by SXRWahrheit** [comment]
Sorry, you don't ask for versions so I assumed everyone updates before reporting.

```
[07:36:39] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-65e8124-79e55b6 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
[07:36:47] [Server thread/INFO]: [MagicSpells] Loading MagicSpells v3.5-dev-1708041909
[07:36:42] [Server thread/INFO]: [Effect Library] Loading EffectLib v5.4
```

```
[07:45:46] [Server thread/INFO]: Wahrheit issued server command: /cast forcebomb
[07:45:46] [Server thread/INFO]: [PLAYERCOMMAND} Wahrheit: [-129 88 149] => "/cast forcebomb"
[07:45:46] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cast' in plugin MagicSpells v3.5-dev-1708041909
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-65e8124-79e55b6]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-65e8124-79e55b6]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[server.jar:git-Spigot-65e8124-79e55b6]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1386) [server.jar:git-Spigot-65e8124-79e55b6]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1221) [server.jar:git-Spigot-65e8124-79e55b6]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-65e8124-79e55b6]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-65e8124-79e55b6]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-65e8124-79e55b6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-65e8124-79e55b6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-65e8124-79e55b6]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-65e8124-79e55b6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-65e8124-79e55b6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-65e8124-79e55b6]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.LivingEntity.getTargetBlock(Ljava/util/HashSet;I)Lorg/bukkit/block/Block;
	at com.nisovin.magicspells.util.BlockUtils.getTargetBlock(BlockUtils.java:42) ~[?:?]
	at com.nisovin.magicspells.Spell.getTargetedBlock(Spell.java:1900) ~[?:?]
	at com.nisovin.magicspells.spells.targeted.ForcebombSpell.castSpell(ForcebombSpell.java:45) ~[?:?]
	at com.nisovin.magicspells.Spell.handleCast(Spell.java:1272) ~[?:?]
	at com.nisovin.magicspells.Spell.cast(Spell.java:1196) ~[?:?]
	at com.nisovin.magicspells.Spell.cast(Spell.java:1186) ~[?:?]
	at com.nisovin.magicspells.CastCommand.onCommand(CastCommand.java:321) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-65e8124-79e55b6]
	... 15 more
```

**Comment by TheComputerGeek2** [comment]
I my hope is that people would be up to date, but sadly, that is rarely the case and so it is much faster for me to just ask for versions.

As for this error, it looks like some method signature was changed in 1.12.1.

**Comment by SXRWahrheit** [comment]
Need anything else from me for this?
